export const NUEVO_NEGOCIO = "NUEVO_NEGOCIO";
export const VER_NEGOCIOS = "VER_NEGOCIOS";
export const USER_CONFIG = "USER_CONFIG";
export const QR_READER = "QR_READER";
export const TURNOS = "TURNOS";
//OPCIONES DEL MENU INFERIOR
