/* ACCIONES AL CARGAR UN NUEVO NEGOCIO */
export const NEW_NEGOCIO = "NEW_NEGOCIO";
export const CENTER_MAP = "CENTER_MAP";
export const SWITCH_MENU = "SWITCH_MENU";
export const ADD_NEGOCIO = "ADD_NEGOCIO";
export const SELECT_MARKER = "SELECT_MARKER";
export const DELETE_NEGOCIO = "DELETE_NEGOCIO";
export const SET_CENTER_MAP = "SET_CENTER_MAP";
export const CHANGE_CENTER_TO_SETTED = "CHANGE_CENTER_TO_SETTED";
export const QR_READ = "QR_READ";
export const QR_PERMISSIONS = "QR_PERMISSIONS";


export const actions = {
  SET_DATA_NEGOCIO: "SET_DATA_NEGOCIO",
  SET_HORARIOS_NEGOCIO: "SET_HORARIOS_NEGOCIO",
  LOGGED: "LOGGED",
  TOAST: "TOAST",
  SET_REGISTER_DATA: "SET_REGISTER_DATA",
  SHOW_INFO_NEGOCIOS: "SHOW_INFO_NEGOCIOS",
};
