/* ACCIONES AL CARGAR UN NUEVO NEGOCIO */
export const NEW_NEGOCIO = "NEW_NEGOCIO";
export const CENTER_MAP = "CENTER_MAP";
export const SWITCH_MENU = "SWITCH_MENU";
export const ADD_NEGOCIO = "ADD_NEGOCIO";
